r64bits-dev/chatwoot

Gemfile, Gemfile.lock, app/models/account.rb, app/models/trigger.rb, config/database.yml, docker-compose.yaml, docker/Dockerfile, docker/entrypoints/webpack.sh
correction into docker local some export in webpack
=> feat: add docker-compose to run official

lib/tasks/db_enhancements.rake
=> feat: add skip migrate if connector is not postgres

config/database.yml
hot fix to skip database tasks
=> fix: database database skip database tasks

spec/builders/v2/report_builder_spec.rb, spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb, spec/controllers/api/v1/widget/direct_uploads_controller_spec.rb, spec/controllers/devise/omniauth_callbacks_controller_spec.rb, spec/controllers/platform/api/v1/accounts_controller_spec.rb, spec/controllers/platform/api/v1/users_controller_spec.rb, spec/controllers/slack_uploads_controller_spec.rb, spec/controllers/super_admin/accounts_controller_spec.rb, spec/controllers/super_admin/agent_bots_controller_spec.rb, spec/controllers/super_admin/app_config_controller_spec.rb, spec/controllers/super_admin/users_controller_spec.rb, spec/enterprise/controllers/enterprise/api/v1/accounts_controller_spec.rb, spec/enterprise/services/enterprise/billing/create_stripe_customer_service_spec.rb, spec/factories/triggers.rb, spec/helpers/billing_helper_spec.rb, spec/jobs/inboxes/fetch_imap_emails_job_spec.rb, spec/jobs/mutex_application_job_spec.rb, spec/lib/chatwoot_captcha_spec.rb, spec/lib/config_loader_spec.rb, spec/lib/csml_engine_spec.rb, spec/listeners/installation_webhook_listener_spec.rb, spec/mailers/conversation_reply_mailer_spec.rb, spec/models/channel/twilio_sms_spec.rb, spec/models/concerns/avatarable_shared.rb, spec/models/contact_inbox_spec.rb, spec/models/conversation_spec.rb, spec/models/notification_spec.rb, spec/models/trigger_spec.rb, spec/models/user_spec.rb, spec/models/working_hour_spec.rb
addition to fix warning tests to skip error tests
=> Mais 8/add more specs

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
correction into layout email
https://brainitsolutions.atlassian.net/browse/MAIS-35
=> feat: remove wrap max with

app/controllers/devise_overrides/sessions_controller.rb, app/controllers/platform/api/v1/users_controller.rb, app/javascript/dashboard/i18n/locale/en/agentMgmt.json, app/javascript/dashboard/i18n/locale/pt/agentMgmt.json, app/javascript/dashboard/i18n/locale/pt_BR/agentMgmt.json
=> feat: add sessions controller

app/builders/agent_builder.rb, app/javascript/dashboard/i18n/locale/en/agentMgmt.json, app/javascript/dashboard/i18n/locale/pt/agentMgmt.json, app/javascript/dashboard/i18n/locale/pt_BR/agentMgmt.json, app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
adição de team na hora de criação de um agent
=> Mais 39/add team account

app/controllers/api/v1/accounts/teams_controller.rb
adição de scope só para o supervsior
=> feat: add teams controller

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
=> feat add conversation view scss

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
=> feat: add correction again

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
=> feat: add conversation

app/builders/v2/report_builder.rb, app/helpers/api/v2/accounts/reports_helper.rb, app/helpers/report_helper.rb, app/javascript/dashboard/routes/dashboard/settings/reports/TriggerReports.vue, http/report.http
correção de filtros no relatório de triggers
=> Mais 41/add range on filter

app/builders/v2/report_builder.rb, app/helpers/api/v2/accounts/reports_helper.rb, app/helpers/report_helper.rb, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/routes/dashboard/settings/reports/TriggerReports.vue, http/report.http
=> Master to Develop

app/builders/v2/report_builder.rb, app/helpers/report_helper.rb
=> feat: add report builder

app/javascript/dashboard/components/buttons/ResolveAction.vue, app/javascript/dashboard/components/widgets/conversation/AddLabelModal.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/pt/conversation.json, app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
adição de pop para adicionar tag
=> Mais 16/add conversation label pop

app/javascript/dashboard/api/reports.js, app/javascript/dashboard/store/modules/reports.js
=> feat: remove timezone

app/javascript/dashboard/components/buttons/ResolveAction.vue
=> feat: resolve action

app/builders/v2/report_builder.rb, app/helpers/report_helper.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/routes/dashboard/settings/reports/TriggerReports.vue, app/javascript/dashboard/store/modules/reports.js
feat: add report builder correction final attempt to correction timezone
=> feat: add report builder correction final attempt to correction timezone

app/builders/v2/report_builder.rb, app/helpers/report_helper.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/components/buttons/ResolveAction.vue, app/javascript/dashboard/routes/dashboard/settings/reports/TriggerReports.vue, app/javascript/dashboard/store/modules/reports.js
feat: add report builder correction final attempt to correction timezone
=> Main -> develop

enterprise/app/helpers/super_admin/features.yml
remoção dos features featurable custom branding
=> feat: add feature custom branding

enterprise/app/controllers/enterprise/super_admin/app_configs_controller.rb
=> feat: add app config

app/controllers/api/v2/accounts/reports_controller.rb, app/helpers/report_helper.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/routes/dashboard/settings/reports/InboxReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue, app/models/conversation.rb, http/report.http
adição de filtro pelo agent também, que dai na caixa de entrada, voce também pode visualizar o agent
=> Mais 50/add filter by agent

app/helpers/report_helper.rb, app/models/conversation.rb, app/models/reporting_event.rb
=> feat: add report helper

app/helpers/report_helper.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue, app/javascript/dashboard/store/modules/reports.js, app/models/message.rb, http/report.http
correções de filter corrections 
=> Mais 50/add filter corrections

.env.example, app/javascript/dashboard/components/app/UpdateBanner.vue, app/javascript/dashboard/routes/dashboard/settings/account/Index.vue, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, config/application.rb, config/locales/devise.en.yml, config/locales/devise.es.yml, config/locales/devise.pt.yml, config/locales/devise.pt_BR.yml
https://brainitsolutions.atlassian.net/browse/MAIS-51
https://brainitsolutions.atlassian.net/browse/MAIS-52
=> Mais 51/add locales mailers

app/javascript/dashboard/App.vue
=> feat: remove banner update

app/javascript/dashboard/mixins/aiMixin.js, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml, lib/integrations/openai/processor_service.rb, lib/integrations/openai_base_service.rb, lib/json_renderer.rb
Feature para mostrar no open ai se já excedeu a cota
=> Mais 53/add show open ai integrations

app/javascript/dashboard/routes/dashboard/conversation/tickets/TicketsList.vue
adição de correção da lista quando nào tem tickets na conversa
=> feat: add tickets list

app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
tentativa de correção para o whatsapp
=> feat: add deep symbolize keys

app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
=> feat: add incoming

app/controllers/webhooks/whatsapp_controller.rb, app/jobs/webhooks/whatsapp_events_job.rb, app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
=> feat: add fix

app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/widgets/forms/TextArea.vue, app/javascript/dashboard/i18n/locale/en/tickets.json, app/javascript/dashboard/i18n/locale/pt/tickets.json, app/javascript/dashboard/i18n/locale/pt_BR/tickets.json, app/javascript/dashboard/routes/dashboard/tickets/TicketView.vue, app/javascript/dashboard/routes/dashboard/tickets/components/MoreActionsDropdown.vue, app/javascript/dashboard/routes/dashboard/tickets/components/TicketDetails.vue, app/javascript/dashboard/store/modules/tickets.js, app/javascript/widget/components/Form/TextArea.vue
add more finish details to tickets reports
=> Mais 56/add more details

app/controllers/api/v1/accounts/tickets_controller.rb, app/javascript/dashboard/components/CustomTicketModal.vue, app/javascript/dashboard/i18n/locale/en/report.json, app/javascript/dashboard/i18n/locale/pt/report.json, app/javascript/dashboard/i18n/locale/pt_BR/report.json, app/javascript/dashboard/routes/dashboard/tickets/components/MoreActionsDropdown.vue, app/javascript/dashboard/routes/dashboard/tickets/components/TicketAgentsTableComponent.vue, app/javascript/dashboard/store/modules/tickets.js, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml
=> Mais 56/fix some translate

app/controllers/webhooks/whatsapp_controller.rb
fix 
- [] New feature (non-breaking change which adds functionality)
=> feat: add whatsapp controller

app/controllers/api/v1/accounts/tickets_controller.rb, app/controllers/concerns/access_token_auth_helper.rb, app/controllers/platform/api/v1/tickets_controller.rb, app/helpers/api/v2/tickets/ticket_helper.rb, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml, config/routes.rb, http/platform/ticket.http, http/platform/user.http, http/ticket.http
adição para parametros e acesso ao token para rotas publicas
=> feat: add access token

app/controllers/api/v1/accounts/tickets_controller.rb, app/javascript/dashboard/api/tickets.js, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/i18n/locale/pt/settings.json, app/javascript/dashboard/i18n/locale/pt_BR/settings.json, app/javascript/dashboard/routes/dashboard/tickets/TicketView.vue, app/javascript/dashboard/store/modules/tickets.js, app/models/ticket.rb, spec/factories/cart_items.rb, spec/factories/carts.rb, spec/factories/products.rb, spec/factories/tickets.rb
adição de sidebar dos marcadores
=> feat: add sidebar labels

app/builders/v2/report_tickets_builder.rb, app/javascript/dashboard/i18n/locale/en/report.json, app/javascript/dashboard/i18n/locale/pt/report.json, app/javascript/dashboard/i18n/locale/pt_BR/report.json, app/javascript/dashboard/mixins/time.js, app/javascript/dashboard/routes/dashboard/tickets/components/TicketAgentsTableComponent.vue, http/report.http
adição de tempo médio de solução
=> feat: add report tickets builder

app/javascript/dashboard/routes/dashboard/settings/reports/TicketsReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue, app/javascript/dashboard/routes/dashboard/tickets/components/TicketAgentsTableComponent.vue
=> feat: add tickets reports filter by period

app/javascript/dashboard/components/CustomTicketModal.vue, app/javascript/dashboard/routes/dashboard/tickets/components/MoreActionsDropdown.vue
adição de algumas features para poder melhorar a experiencia do usuário principalmente em temas noturnos
=> feat: add custom ticket modal

app/controllers/api/v1/accounts/tickets_controller.rb, app/views/api/v1/accounts/tickets/index.json.jbuilder
adição de paginação no index dos tickets
=> feat: add index ticket controller.rb

app/javascript/dashboard/store/modules/tickets.js
=> feat: add deploy tickets fixing

app/controllers/api/v1/accounts/tickets_controller.rb, app/helpers/api/v2/tickets/ticket_helper.rb
=> feat: add build with account

app/controllers/api/v1/accounts/tickets_controller.rb, app/helpers/api/v2/tickets/ticket_helper.rb, app/javascript/dashboard/store/modules/tickets.js
=> feat: add controller fixing

app/controllers/api/base_controller.rb, app/controllers/api/v1/accounts/conversations/assignments_controller.rb, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue, app/javascript/dashboard/routes/dashboard/settings/reports/TicketsReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue, app/javascript/dashboard/routes/dashboard/tickets/components/TicketAgentsTableComponent.vue, app/javascript/dashboard/store/modules/conversations/actions.js, app/models/user.rb, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml, lib/custom_exceptions/agent.rb, lib/custom_exceptions/base.rb, lib/custom_exceptions/team.rb
Não dar assign para agents que não estiverem online
=> feat:  assigment offline 

.gitignore, app/controllers/api/v1/accounts/tickets_controller.rb
=> feat: update ticket controller

app/javascript/dashboard/components/widgets/forms/PhoneInput.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/BandwidthSms.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
=> feat: add Phone on Configuration Whatsapp

app/javascript/dashboard/i18n/locale/en/labelsMgmt.json, config/locales/pt_BR.yml
=> feat: add labels improvements

app/models/contact.rb, app/models/conversation.rb
adição de mais tipos para identificar que é um grupo de whats
=> feat: add conversation group

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/api/utils/string.js, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/store/modules/contacts/actions.js, app/views/api/v1/accounts/contacts/show.json.jbuilder, app/views/api/v1/conversations/partials/_conversation.json.jbuilder, app/views/api/v1/models/_contact.json.jbuilder, docker-compose.yaml, http/contact.http, http/conversation/conversation.http
=> feat: add contact info

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/i18n/locale/pt/contact.json, app/javascript/dashboard/i18n/locale/pt_BR/contact.json, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/views/api/v1/accounts/contacts/show.json.jbuilder, app/views/api/v1/models/_contact.json.jbuilder
adição de visualização da equipe
=> feat: add show team in conversation sidebar

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/api/utils/string.js, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/i18n/locale/pt/contact.json, app/javascript/dashboard/i18n/locale/pt_BR/contact.json, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/store/modules/contacts/actions.js, app/views/api/v1/accounts/contacts/show.json.jbuilder, app/views/api/v1/conversations/partials/_conversation.json.jbuilder, app/views/api/v1/models/_contact.json.jbuilder, docker-compose.yaml, http/contact.http, http/conversation/conversation.http
adição de protocolo, e visualização do time no grid
=> Develop -> Main

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue, app/javascript/shared/helpers/Validators.js
=> feat: add validator contact form

app/javascript/dashboard/routes/dashboard/settings/reports/TeamReports.vue
feat: add team reports filter agents
=> feat: add team reports filter agents

app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js, app/javascript/dashboard/components/layout/config/sidebarItems/tickets.js
correção nas visões de tickets
=> feat: add primary menu remove ticket required feature flag

app/builders/v2/billing_period.rb, app/builders/v2/metrics_data.rb, app/builders/v2/product_details.rb, app/builders/v2/report_invoices_builder.rb, app/controllers/super_admin/products_controller.rb, app/dashboards/product_dashboard.rb, app/helpers/date_range_helper.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/widgets/chart/LineChart.js, app/javascript/dashboard/i18n/locale/pt_BR/report.json, app/javascript/dashboard/routes/dashboard/settings/reports/InvoiceReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/invoices/GraphInvoices.vue, app/javascript/dashboard/routes/dashboard/settings/reports/constants.js, app/javascript/dashboard/store/modules/reports/invoice.js, app/models/account.rb, app/models/product.rb, app/models/reporting_event.rb, config/locales/pt_BR.yml, config/routes.rb, db/migrate/20240923194557_add_identifier_to_existings_products.rb, db/schema.rb, db/seeds.rb, enterprise/app/models/enterprise/account.rb, http/report.http
=> feat: add report invoice builder

app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/dashboard/i18n/locale/pt/generalSettings.json, app/javascript/dashboard/i18n/locale/pt_BR/generalSettings.json, app/javascript/dashboard/routes/dashboard/settings/account/Index.vue, app/views/api/v1/models/_account.json.jbuilder, app/views/api/v1/models/_product.json.jbuilder, enterprise/app/models/enterprise/account.rb
=> Mais 123/add name and description product

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue, app/models/channel/whatsapp.rb, app/services/whatsapp/providers/whatsapp_cloud_service.rb, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml, lib/custom_exceptions/account.rb
=> feat: add cloud whatsapp cloud service

app/helpers/phone_helper.rb, app/jobs/event_dispatcher_job.rb, app/jobs/webhooks/whatsapp_events_job.rb, app/services/evolution/find_participants_service.rb, app/services/whatsapp/send_on_whatsapp_service.rb
=> Mais 132/add event dispatcher

app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue, app/javascript/dashboard/i18n/locale/en/whatsappTemplates.json, app/javascript/dashboard/i18n/locale/pt/whatsappTemplates.json, app/javascript/dashboard/i18n/locale/pt_BR/whatsappTemplates.json, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/services/base/send_on_channel_service.rb, app/services/whatsapp/providers/base_service.rb, app/services/whatsapp/providers/whatsapp_cloud_service.rb, app/services/whatsapp/send_on_whatsapp_service.rb, config/locales/pt_BR.yml, lib/custom_exceptions/account.rb
=> feat: add templates buttons

app/controllers/super_admin/products_controller.rb, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml
This pull request includes several updates to the `SuperAdmin::ProductsController` and localization files to improve error handling and provide better user feedback.
* [`app/controllers/super_admin/products_controller.rb`](diffhunk://#diff-6c43168a88b831b1956c9d250ce3a205433b0d2e65ec241f235a3afd7b099bc1L3-R15): Replaced the `validate_details!` method with `parse_details` to better handle JSON parsing and required keys validation. Added specific error messages for missing keys and JSON parsing errors. [[1]](diffhunk://#diff-6c43168a88b831b1956c9d250ce3a205433b0d2e65ec241f235a3afd7b099bc1L3-R15) [[2]](diffhunk://#diff-6c43168a88b831b1956c9d250ce3a205433b0d2e65ec241f235a3afd7b099bc1L13-L27)
* [`config/locales/en.yml`](diffhunk://#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd …
=> feat: Add validation for required keys in product details

app/controllers/api/v1/accounts/assignable_agents_controller.rb, app/controllers/api/v1/accounts/conversations/assignments_controller.rb, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/NetworkNotification.vue, app/javascript/shared/helpers/BaseActionCableConnector.js, app/models/user.rb, config/initializers/rack_attack.rb, config/locales/en.yml, config/locales/pt.yml, config/locales/pt_BR.yml, lib/custom_exceptions/conversation.rb
This pull request introduces several changes aimed at improving agent assignment logic, enhancing security, and updating localization files. Below are the most important changes grouped by theme:
* [`app/controllers/api/v1/accounts/assignable_agents_controller.rb`](diffhunk://#diff-bfcb675834f79a42c2bc8931e9fde2184942c1c7c9da7abba8cdcf15d9fb913cR10-R23): Updated the logic to filter agents based on their team membership and whether the current user is an administrator. (`[app/controllers/api/v1/accounts/assignable_agents_controller.rbR10-R23](diffhunk://#diff-bfcb675834f79a42c2bc8931e9fde2184942c1c7c9da7abba8cdcf15d9fb913cR10-R23)`)
* [`app/controllers/api/v1/accounts/conversations/assignments_controller.rb`](diffhunk://#diff-03b38c035ee0ec182f441ce81d11220d1a090b999e0e9b40ad78097c3045acd2R …
=> Mais 159/add some improvements

app/controllers/api/v1/accounts/conversations_controller.rb, app/helpers/api/v1/conversations_helper.rb, app/javascript/dashboard/App.vue, app/javascript/dashboard/api/inbox/conversation.js, app/javascript/dashboard/store/modules/conversations/actions.js, config/routes.rb, lib/online_status_tracker.rb
This pull request introduces a new feature to automatically assign open conversations to agents. The changes span across multiple files to implement this functionality, including the controller, helper, frontend components, and routes. Here are the most important changes:
* [`app/controllers/api/v1/accounts/conversations_controller.rb`](diffhunk://#diff-8fb41fe61719f585df82857783e71659e44f32cbec1d4e71acd3c95323d7833eL6-R6): Added a new action `need_to_assign_agent` to handle the assignment of open conversations to agents. Updated `before_action` to include the new action. [[1]](diffhunk://#diff-8fb41fe61719f585df82857783e71659e44f32cbec1d4e71acd3c95323d7833eL6-R6) [[2]](diffhunk://#diff-8fb41fe61719f585df82857783e71659e44f32cbec1d4e71acd3c95323d7833eR64-R72)
* …
=> Mais 173/add conversation controller

app/controllers/api/v1/accounts/conversations_controller.rb, app/controllers/api/v1/profiles_controller.rb, app/helpers/api/v1/conversations_helper.rb, app/jobs/channels/whatsapp/templates_sync_scheduler_job.rb
This pull request includes changes to the `app/jobs/channels/whatsapp/templates_sync_scheduler_job.rb` file. The changes focus on adjusting the scheduling of WhatsApp template sync jobs.
Scheduling adjustments:
* [`app/jobs/channels/whatsapp/templates_sync_scheduler_job.rb`](diffhunk://#diff-950833594f1ebe16a6bb4bdd6c3df6dd8e05c147f9cb3582857746efef4d9ef3L6-R6): Changed the time interval for syncing WhatsApp message templates from 3 hours to 5 minutes.
=> MAIS-253 - Change Template Sync Job from 3 Hours to 5 Minutes

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/modules/search/components/ModalCreateNewConversation.vue
This pull request includes several changes to the `contacts_controller.rb` and `ModalCreateNewConversation.vue` files to improve code organization and functionality. The changes primarily focus on extracting methods for better readability and refactoring the Vue component to handle inbox selection more effectively.
* [`app/controllers/api/v1/accounts/contacts_controller.rb`](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b2edec2cbadc28c36b21L93-R94): Extracted the `find_or_create_contact` and `create_conversation_and_message` methods from the `contact_and_message` method to improve readability and maintainability. [[1]](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b2edec2cbadc28c36b21L93-R94) [[2]](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b …
=> Mais 295/add conversation

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/QRCodeWhatsapp.vue, app/services/whatsapp/providers/whatsapp_cloud_service.rb, app/views/api/v1/models/_contact_inbox.json.jbuilder
This pull request includes several changes to the `QRCodeWhatsapp.vue`, `whatsapp_cloud_service.rb`, and `_contact_inbox.json.jbuilder` files to improve code maintainability and functionality. The most important changes are:
* [`app/javascript/dashboard/routes/dashboard/settings/inbox/channels/QRCodeWhatsapp.vue`](diffhunk://#diff-227cb2afa3a1c87044fdd5b2f266674f16be66bacf1ad9edc0f7b77fed86801dL52-R52): Commented out multiple sections of unused HTML code to clean up the file. [[1]](diffhunk://#diff-227cb2afa3a1c87044fdd5b2f266674f16be66bacf1ad9edc0f7b77fed86801dL52-R52) [[2]](diffhunk://#diff-227cb2afa3a1c87044fdd5b2f266674f16be66bacf1ad9edc0f7b77fed86801dL62-R64) [[3]](diffhunk://#diff-227cb2afa3a1c87044fdd5b2f266674f16be66bacf1ad9edc0f7b77fed86801dL74-R74)
* …
=> Mais 331/remove checkbox in qr code

app/controllers/api/v1/accounts/tickets_controller.rb, app/javascript/dashboard/routes/dashboard/tickets/TicketContent.vue
This pull request includes changes to the `TicketsController` and improvements to the `TicketContent.vue` component to enhance the ticket listing and display functionality, especially for mobile devices. The most important changes include adding a search filter to the tickets controller, updating the layout and styles of the ticket list, and adding mobile responsiveness.
Enhancements to ticket listing:
* [`app/controllers/api/v1/accounts/tickets_controller.rb`](diffhunk://#diff-0d23a8ca259758eab015dc8c479eac1df10286de7e4139891e5b559629d6cb37R14): Added a search filter to the ticket listing by including the `search_by_params` method.
Improvements to `TicketContent.vue` component:
* [`app/javascript/dashboard/routes/dashboard/tickets/TicketContent.vue`](diffhunk://#diff-9975b79fa734917291fca …
=> Mais 312/add tickets view

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/ui/WootToogle.vue, app/javascript/dashboard/i18n/locale/en/search.json, app/javascript/dashboard/i18n/locale/pt/search.json, app/javascript/dashboard/i18n/locale/pt_BR/search.json, app/javascript/dashboard/modules/search/components/ModalCreateNewConversation.vue
This pull request introduces a feature to assign the current user to a conversation and includes various related changes across the codebase. The most important changes include updates to the backend controller, frontend API client, UI components, and localization files.
Backend updates:
* [`app/controllers/api/v1/accounts/contacts_controller.rb`](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b2edec2cbadc28c36b21R141-R145): Added logic to assign the current user to a conversation if the `assign_current_user` parameter is present. [[1]](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b2edec2cbadc28c36b21R141-R145) [[2]](diffhunk://#diff-9c3ceeb825474ffa043601be1af67d83b15daf068a33b2edec2cbadc28c36b21L189-R195)
Frontend updates:
* …
=> feat: add assign current user option in conversation creation

app/controllers/api/v1/accounts/conversations_controller.rb, app/finders/conversation_finder.rb, app/models/user.rb, app/services/conversations/filter_service.rb
improve conversation filtering and access control for non-administrator users.
- Enhance conversation filtering to respect team and inbox permissions
- Modify inbox selection logic to support administrator and agent access levels
- Add account_user method to User model for easier account context retrieval
=> MAIS-340 - Improve conversation filtering and access control for non-administrator users

app/builders/contact_inbox_builder.rb, app/builders/conversation_builder.rb, app/builders/messages/message_builder.rb, app/controllers/api/v1/accounts/contacts_controller.rb, app/controllers/api/v1/accounts/conversations_controller.rb, app/finders/conversation_finder.rb, app/helpers/phone_helper.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/ui/WootToogle.vue, app/javascript/dashboard/i18n/locale/en/search.json, app/javascript/dashboard/i18n/locale/pt/search.json, app/javascript/dashboard/i18n/locale/pt_BR/search.json, app/javascript/dashboard/modules/search/components/ModalCreateNewConversation.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/tickets/TicketContent.vue, app/jobs/webhooks/whatsapp_events_job.rb, app/models/inbox.rb, app/models/user.rb, app/services/auto_assignment/agent_assignment_service.rb, app/services/auto_assignment/inbox_round_robin_service.rb, app/services/conversations/filter_service.rb, db/migrate/20250220143023_change_lock_to_single_conversation_default_in_inboxes.rb, db/schema.rb
This pull request includes multiple changes across various files to improve functionality and add new features. The most important changes include updates to the `generate_source_id` method, modifications to conversation handling, enhancements to message processing, and the addition of a new UI component.
* [`app/builders/contact_inbox_builder.rb`](diffhunk://#diff-d66798e70e56db1d8853fa28093c501f53fe08648f250cbdd0d704f4c738ad73L22-R24): Updated the `generate_source_id` method to include `Channel::Api` in the `phone_source_id` case and adjusted the cases accordingly.
* [`app/builders/conversation_builder.rb`](diffhunk://#diff-e20983485402ca35be6f23f3dcf9b468cf184e1527e47e661d9d234c9e53f737L20-R20): Modified the `look_up_existing_conversation` method to retrieve the last conversation …
=> Merge: Develop -> Main

app/builders/conversation_builder.rb
Ensure only open conversations are returned when locking to single conversation.
=> MAIS-343 - Ensure only open conversations are returned when locking to single conversation.

app/builders/conversation_builder.rb
Ensure only open conversations are returned when locking to single conversation.
=> MAIS 343 - Ensure only open conversations are returned when locking to single conversation

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/components/widgets/forms/PhoneInput.vue, app/javascript/dashboard/i18n/locale/pt_BR/search.json, app/javascript/dashboard/modules/search/components/ModalCreateNewConversation.vue
=> add feature create message with team selected

app/javascript/shared/helpers/BaseActionCableConnector.js
=> https://brainitsolutions.atlassian.net/browse/MAIS-348

app/builders/messages/instagram/message_builder.rb, app/builders/messages/message_builder.rb, app/controllers/api/v1/accounts/tickets_controller.rb, app/helpers/api/v2/tickets/ticket_helper.rb, app/javascript/shared/helpers/BaseActionCableConnector.js
=> merge from develop

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
=> bugfix addBlock to send message if not assign
